#############################################################################
# Makefile for building: Mocca
# Generated by qmake (2.01a) (Qt 4.6.2) on: ven. avr. 1 23:09:31 2011
# Project:  Mocca.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile Mocca.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = moccamain.cpp \
		main.cpp \
		moccavideo.cpp moc_moccamain.cpp \
		moc_moccavideo.cpp
OBJECTS       = moccamain.o \
		main.o \
		moccavideo.o \
		moc_moccamain.o \
		moc_moccavideo.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Mocca.pro
QMAKE_TARGET  = Mocca
DESTDIR       = 
TARGET        = Mocca

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_moccamain.h ui_moccavideo.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Mocca.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile Mocca.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile Mocca.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Mocca1.0.0 || $(MKDIR) .tmp/Mocca1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Mocca1.0.0/ && $(COPY_FILE) --parents moccamain.h moccavideo.h moccaglobals.h .tmp/Mocca1.0.0/ && $(COPY_FILE) --parents moccamain.cpp main.cpp moccavideo.cpp .tmp/Mocca1.0.0/ && $(COPY_FILE) --parents moccamain.ui moccavideo.ui .tmp/Mocca1.0.0/ && (cd `dirname .tmp/Mocca1.0.0` && $(TAR) Mocca1.0.0.tar Mocca1.0.0 && $(COMPRESS) Mocca1.0.0.tar) && $(MOVE) `dirname .tmp/Mocca1.0.0`/Mocca1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Mocca1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_moccamain.cpp moc_moccavideo.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_moccamain.cpp moc_moccavideo.cpp
moc_moccamain.cpp: moccaglobals.h \
		moccamain.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) moccamain.h -o moc_moccamain.cpp

moc_moccavideo.cpp: moccavideo.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) moccavideo.h -o moc_moccavideo.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_moccamain.h ui_moccavideo.h
compiler_uic_clean:
	-$(DEL_FILE) ui_moccamain.h ui_moccavideo.h
ui_moccamain.h: moccamain.ui
	/usr/bin/uic-qt4 moccamain.ui -o ui_moccamain.h

ui_moccavideo.h: moccavideo.ui
	/usr/bin/uic-qt4 moccavideo.ui -o ui_moccavideo.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

moccamain.o: moccamain.cpp moccamain.h \
		moccaglobals.h \
		ui_moccamain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moccamain.o moccamain.cpp

main.o: main.cpp moccamain.h \
		moccaglobals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moccavideo.o: moccavideo.cpp moccavideo.h \
		ui_moccavideo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moccavideo.o moccavideo.cpp

moc_moccamain.o: moc_moccamain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_moccamain.o moc_moccamain.cpp

moc_moccavideo.o: moc_moccavideo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_moccavideo.o moc_moccavideo.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

